### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by danger89** [github/cmark-gfm#228]
Hello devs?

Is this project even active? Please update with upstream. And roll-out a new version 👍🏽 .. Plz?

Also take a look at the open PRs.

Regards,
Melroy vd Berg

**Comment by digitalmoksha** [comment]
@kivikakk I think you've moved on from this, but any idea if there is still an effort to maintain this?

**Comment by UziTech** [comment]
looks like @phillmv is working on this repo.

**Comment by kivikakk** [comment]
Indeed, I left GitHub in December 2019. It does look like there's new movement from @phillmv, which is awesome. Phill, please feel free to open PRs to Commonmarker when updating cmark-gfm! :heart:

**Comment by phillmv** [comment]
@kivikakk shall do, much obliged!

@UziTech et al, this project is still used to render the very text you are reading now, and swapping it out without a perfect replacement would cause so much hassle that, speaking for myself, I wager it will continue to be used until the heat death of the universe (tho, no guarantees).

That said, as you can tell, this project is not being _actively_ maintained. I am told that this may change in the coming months, once we conclude an internal re-org, but that is not for me to decide.

I myself am doing some clean up work as a hobby, because I became obsessed with fixing some of the bugs with the footnote extension. While I'm at it, we'll cut another release to match the security advisory (I actually work on security advisories), but after that I doubt I will have the time/energy to try to merge upstream.

Hope this message finds you well, and with that I shall close this issue.

**Comment by digitalmoksha** [comment]
@phillmv thanks for the update!

Do you think there is any chance of updating to the latest CommonMark spec, or that's out a few months?

Glad to hear this is still active!

**Comment by phillmv** [comment]
@digitalmoksha That's at best out a few months out, sorry - it's a rather big lift I'm not going to volunteer to do.

By sheer coincidence, I may have been able to speed up the timeline a bit, but it is out of my hands.

**Comment by danger89** [comment]
As issue creator, I want to thank you for your time and efforts in advance. I hope you will be able to update this repo. Otherwise, maybe look for volunteers, either inside GitHub or outside the teams.
